name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - apps/automation-gateway/src/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: TEST 
        run: echo "TESTING.." && exit 1

      - name: Build Docker image
        run: |
          docker build -t myusername/myapp:latest .
      
      - name: Push Docker image
        run: |
          docker push myusername/myapp:latest

      - name: SSH into EC2 and update container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull myusername/myapp:latest
            # Run container or restart your app
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 myusername/myapp:latest